openapi: 3.1.0
info:
  title: agente_mcp Manual Runner API
  version: 0.1.0
  description: >-
    Contract that mirrors the responsibilities da refatoração. Although the project
    roda via `python agente_mcp/main.py`, estes endpoints descrevem os fluxos
    equivalentes para orientar integrações futuras e guiar o desenho dos módulos.
servers:
  - url: http://localhost:8001
    description: Placeholder caso o runner ganhe interface HTTP
paths:
  /sessions:
    post:
      summary: Executa uma sessão completa do agente multi-servidor
      operationId: runSession
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                thread_id:
                  type: string
                  default: manual-run
                questions:
                  type: array
                  items:
                    type: string
                  minItems: 1
                  description: Lista de prompts executados sequencialmente
                auto_start_servers:
                  type: boolean
                  default: true
                log_level:
                  type: string
                  enum: [DEBUG, INFO, ERROR]
                  default: INFO
              required: [questions]
      responses:
        '200':
          description: Execução concluída com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  messages:
                    type: array
                    items:
                      type: object
                      properties:
                        role:
                          type: string
                        content:
                          type: string
                  run_log:
                    type: array
                    items:
                      type: object
                      properties:
                        tool_name:
                          type: string
                        status:
                          type: string
                        duration_ms:
                          type: integer
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        category:
                          type: string
                        message:
                          type: string
        '400':
          description: Configuração inválida (variáveis ausentes, conflitos de ferramentas)
        '502':
          description: Algum servidor MCP não respondeu ou retornou payload inválido
  /servers:
    get:
      summary: Lista os perfis de servidores ativos
      operationId: listServers
      responses:
        '200':
          description: Coleção de perfis carregados
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ServerProfile'
    post:
      summary: Cadastra ou atualiza um perfil de servidor MCP
      operationId: upsertServer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServerProfile'
      responses:
        '204':
          description: Perfil salvo e pronto para ser usado em execuções futuras
        '409':
          description: Conflito de nome de servidor ou transporte não suportado
components:
  schemas:
    ServerProfile:
      type: object
      required: [name, transport, endpoint]
      properties:
        name:
          type: string
          pattern: '^[a-z0-9_]+$'
        transport:
          type: string
          enum: [stdio, sse]
        endpoint:
          type: string
          description: Caminho local ou URL SSE
        auto_start:
          type: boolean
          default: true
        env:
          type: object
          additionalProperties:
            type: string
        timeout_seconds:
          type: integer
          minimum: 1
