openapi: 3.1.0
info:
  title: Reflection Agent Runner
  version: 0.1.0
  description: >
    Trigger the baseline reflection agent that answers “O que é importante para um programador aprender”
    using a fixed number of LangGraph generate→reflect iterations.
paths:
  /agents/reflection/basic-run:
    post:
      summary: Execute the baseline reflection agent
      description: >
        Runs the agent with the repository-standard iteration configuration and returns every draft,
        reflection note, and the final answer for reviewer inspection.
      requestBody:
        required: false
      responses:
        "200":
          description: Successful execution
          content:
            application/json:
              schema:
                type: object
                required:
                  - question
                  - iteration_limit
                  - drafts
                  - reflections
                  - final_answer
                  - runtime_seconds
                properties:
                  question:
                    type: string
                    const: O que é importante para um programador aprender
                  iteration_limit:
                    type: integer
                    minimum: 1
                    description: Number of generate→reflect cycles executed (includes initial draft).
                  drafts:
                    type: array
                    description: Ordered list of draft responses including the final answer.
                    items:
                      type: object
                      required:
                        - iteration_index
                        - content
                        - improvements_applied
                      properties:
                        iteration_index:
                          type: integer
                          minimum: 0
                        content:
                          type: string
                        improvements_applied:
                          type: array
                          items:
                            type: string
                  reflections:
                    type: array
                    description: Critiques that informed each rewrite after the first draft.
                    items:
                      type: object
                      required:
                        - iteration_index
                        - strengths
                        - gaps
                        - action_items
                        - reuse_flag
                      properties:
                        iteration_index:
                          type: integer
                          minimum: 0
                        strengths:
                          type: array
                          items:
                            type: string
                        gaps:
                          type: array
                          items:
                            type: string
                        action_items:
                          type: array
                          items:
                            type: string
                        reuse_flag:
                          type: boolean
                  final_answer:
                    type: object
                    description: Final draft after the last reflection cycle.
                    allOf:
                      - $ref: "#/paths/~1agents~1reflection~1basic-run/post/responses/200/content/application~1json/schema/properties/drafts/items"
                  runtime_seconds:
                    type: number
                    format: float
                    description: Total execution time for the run.
        "500":
          description: Agent execution failed
          content:
            application/json:
              schema:
                type: object
                required:
                  - error
                properties:
                  error:
                    type: string
